### ISSUE TITLE
Any chance we can migrate this repo to Apache-2.0?

### ISSUE THREAD

**Issue by joyqvq** [arnaucube/poseidon-ark#1]
Similar reason to poseideon-rs, plus some benefit to keep it compatible with arkworks field representation. https://github.com/arnaucube/poseidon-rs/commit/233027d6075a637c29ad84a8a44f5653b81f0410

**Comment by arnaucube** [comment]
Hi, while I prefer GPL style licenses, since poseidon-rs is already on Apache I don't oppose to migrating poseidon-ark also to apache, although I see that you already did it here: https://github.com/MystenLabs/poseidon-ark

One thing to mention also, is that the poseidon-rs & poseidon-ark were done to have a rust implementation of the hash compatible with the circomlib version. But, if you're using arkworks, maybe you are using the arkworks gadget system, if that's the case, there is an arkworks poseidon implementation https://github.com/arkworks-rs/crypto-primitives/blob/main/src/crh/poseidon/mod.rs which is on pair with their gadget poseidon implementation.

In any case, updated this repo to migrate to Apache: https://github.com/arnaucube/poseidon-ark/commit/da4fce71c5d5e8383e794b78cbb537a80ae05eed

**Comment by joyqvq** [comment]
thank you - i think you are missing the change here as well: https://github.com/arnaucube/poseidon-ark/blob/main/Cargo.toml#L6

**Comment by arnaucube** [comment]
oh right. Amended the commit updating the `Cargo.toml`, thanks!

**Comment by joyqvq** [comment]
thank you 🙏
